### ISSUE TITLE
api寄了，这几天一直返回同一张图

### ISSUE THREAD

**Issue by Baimotong** [SonderXiaoming/dailymoyu#5]
如图
![image](https://github.com/SonderXiaoming/dailymoyu/assets/30062345/b3533513-bfcc-4188-8ace-294641993867)
![image](https://github.com/SonderXiaoming/dailymoyu/assets/30062345/e7ec4476-05fb-4af4-8bf0-20a7a2e015c3)

**Comment by SonderXiaoming** [comment]
可能摸鱼了，有没有其他api推荐

**Comment by Baimotong** [comment]
日历作者的公众号上有两个，第一个就是目前您用的这个
![image](https://github.com/SonderXiaoming/dailymoyu/assets/30062345/4fa33782-c633-40dd-9571-2edf708818b2)
大佬可以试试第二个https://api.vvhan.com/api/moyu

https://api.vvhan.com/moyu.html
![image](https://github.com/SonderXiaoming/dailymoyu/assets/30062345/0a37b39c-bcb8-4015-9277-ee56bdf2452b)

**Comment by Baimotong** [comment]
貌似现在原来的又恢复了，目前正常使用中

**Comment by Baimotong** [comment]
您好，最近一直出现这个问题，希望能更换api

**Comment by Hana-Akira** [comment]
<img width="732" alt="moyu" src="https://github.com/SonderXiaoming/dailymoyu/assets/40086110/9673faa5-c79f-4ddf-a6b0-0d3f83e9f384">
自行修改文件即可（图例是第二个api的设置）

**Comment by Baimotong** [comment]
修改后可正常使用，感谢！
